-- Territorial estate loyalty, tax collection and player-managed transport routes.
-- Apply after production_turn_accounting.sql / its migration equivalent.

create table if not exists public.territory_loyalty (
    territory_type text not null check (territory_type in ('province','marker')),
    territory_id bigint not null,
    loyalty jsonb not null default '{"aristocracy":100,"clergy":100,"burghers":100,"peasants":100}'::jsonb,
    updated_at timestamptz not null default now(),
    primary key (territory_type, territory_id)
);
alter table public.territory_loyalty enable row level security;
drop policy if exists "Territory loyalty is publicly readable" on public.territory_loyalty;
create policy "Territory loyalty is publicly readable" on public.territory_loyalty
    for select to anon, authenticated using (true);
revoke all on public.territory_loyalty from anon, authenticated;
grant select on public.territory_loyalty to anon, authenticated;

insert into public.territory_loyalty(territory_type,territory_id,loyalty)
select 'province',p.id,jsonb_build_object(
    'aristocracy',coalesce((sm.settings#>>'{estate_loyalty,aristocracy}')::numeric,100),
    'clergy',coalesce((sm.settings#>>'{estate_loyalty,clergy}')::numeric,100),
    'burghers',coalesce((sm.settings#>>'{estate_loyalty,burghers}')::numeric,100),
    'peasants',coalesce((sm.settings#>>'{estate_loyalty,peasants}')::numeric,100))
from public."Provinces" p left join public.state_mechanics sm on sm.owner=p.owner
on conflict(territory_type,territory_id) do nothing;
insert into public.territory_loyalty(territory_type,territory_id,loyalty)
select 'marker',m.id,jsonb_build_object(
    'aristocracy',coalesce((sm.settings#>>'{estate_loyalty,aristocracy}')::numeric,100),
    'clergy',coalesce((sm.settings#>>'{estate_loyalty,clergy}')::numeric,100),
    'burghers',coalesce((sm.settings#>>'{estate_loyalty,burghers}')::numeric,100),
    'peasants',coalesce((sm.settings#>>'{estate_loyalty,peasants}')::numeric,100))
from public.markers m left join public.state_mechanics sm on sm.owner=m.owner
on conflict(territory_type,territory_id) do nothing;

create table if not exists public.marker_transport_routes (
    id bigint generated by default as identity primary key,
    source_marker_id bigint not null references public.markers(id) on delete cascade,
    destination_marker_id bigint not null references public.markers(id) on delete cascade,
    item_type text not null check (item_type in ('resource','good')),
    item_name text not null,
    quantity_per_turn numeric(12,2) not null check (quantity_per_turn > 0 and quantity_per_turn <= 10000),
    priority smallint not null default 100 check (priority between 1 and 1000),
    created_at timestamptz not null default now(),
    check (source_marker_id <> destination_marker_id),
    unique (source_marker_id,destination_marker_id,item_type,item_name)
);
create index if not exists marker_transport_routes_source_idx on public.marker_transport_routes(source_marker_id,priority,id);
alter table public.marker_transport_routes enable row level security;
drop policy if exists "Transport routes are publicly readable" on public.marker_transport_routes;
create policy "Transport routes are publicly readable" on public.marker_transport_routes
    for select to anon, authenticated using (true);
revoke all on public.marker_transport_routes from anon, authenticated;
grant select on public.marker_transport_routes to anon, authenticated;

create or replace function public.save_marker_transport_route(
    p_source_marker_id bigint,p_destination_marker_id bigint,p_item_type text,p_item_name text,p_quantity_per_turn numeric
) returns jsonb
language plpgsql security definer set search_path = ''
as $function$
declare
    caller_role text;
    caller_owner text;
    source_owner text;
    destination_owner text;
    source_province_owner text;
    destination_province_owner text;
    saved public.marker_transport_routes%rowtype;
    allowed_resources constant text[] := array['Зерно','Древесина','Железная руда','Скот','Камень','Соль','Пушнина','Бивни','Ворвань','Самоцветы','Мёд и Воск','Лён','Морепродукты'];
    allowed_goods constant text[] := array['Топливо','Сукно и Одежда','Инструменты','Оружие и Доспехи','Обработанный камень','Оловина','Бумага'];
begin
    select p.role,p.owner into caller_role,caller_owner from public.profiles p where p.id=(select auth.uid());
    if caller_role is null then raise exception 'Authentication required' using errcode='42501'; end if;
    if p_source_marker_id is null or p_destination_marker_id is null or p_source_marker_id=p_destination_marker_id then raise exception 'Invalid route endpoints'; end if;
    if p_item_type not in ('resource','good') or (p_item_type='resource' and not (p_item_name=any(allowed_resources))) or (p_item_type='good' and not (p_item_name=any(allowed_goods))) then raise exception 'Invalid cargo'; end if;
    if p_quantity_per_turn is null or p_quantity_per_turn<0 or p_quantity_per_turn>10000 then raise exception 'Invalid route quantity'; end if;
    select m.owner,p.owner into source_owner,source_province_owner from public.markers m join public."Provinces" p on p.id=m.province_id where m.id=p_source_marker_id and m.type<>'ruins';
    select m.owner,p.owner into destination_owner,destination_province_owner from public.markers m join public."Provinces" p on p.id=m.province_id where m.id=p_destination_marker_id and m.type<>'ruins';
    if source_owner is null or destination_owner is null or source_owner<>destination_owner or source_owner is distinct from source_province_owner or destination_owner is distinct from destination_province_owner then raise exception 'Both settlements must belong to the same state and controlled provinces'; end if;
    if caller_role<>'admin' and caller_owner is distinct from source_owner then raise exception 'You cannot manage another state transport'; end if;
    if p_quantity_per_turn=0 then
        delete from public.marker_transport_routes where source_marker_id=p_source_marker_id and destination_marker_id=p_destination_marker_id and item_type=p_item_type and item_name=p_item_name;
        return jsonb_build_object('deleted',true,'source_marker_id',p_source_marker_id,'destination_marker_id',p_destination_marker_id,'item_type',p_item_type,'item_name',p_item_name);
    end if;
    insert into public.marker_transport_routes(source_marker_id,destination_marker_id,item_type,item_name,quantity_per_turn)
    values(p_source_marker_id,p_destination_marker_id,p_item_type,p_item_name,p_quantity_per_turn)
    on conflict(source_marker_id,destination_marker_id,item_type,item_name) do update set quantity_per_turn=excluded.quantity_per_turn
    returning * into saved;
    return to_jsonb(saved);
end;
$function$;
revoke all on function public.save_marker_transport_route(bigint,bigint,text,text,numeric) from public,anon;
grant execute on function public.save_marker_transport_route(bigint,bigint,text,text,numeric) to authenticated;

create or replace function public.save_territory_loyalty(p_territory_type text,p_territory_id bigint,p_loyalty jsonb)
returns jsonb language plpgsql security definer set search_path = ''
as $function$
declare caller_role text; normalized jsonb;
begin
    select p.role into caller_role from public.profiles p where p.id=(select auth.uid());
    if caller_role is distinct from 'admin' then raise exception 'Only an administrator can edit territorial loyalty' using errcode='42501'; end if;
    if p_territory_type not in ('province','marker') or p_territory_id is null or jsonb_typeof(p_loyalty)<>'object' then raise exception 'Invalid territory loyalty'; end if;
    if p_territory_type='province' and not exists(select 1 from public."Provinces" where id=p_territory_id) then raise exception 'Province not found'; end if;
    if p_territory_type='marker' and not exists(select 1 from public.markers where id=p_territory_id) then raise exception 'Settlement not found'; end if;
    normalized=jsonb_build_object(
        'aristocracy',greatest(0,least(100,coalesce((p_loyalty->>'aristocracy')::numeric,100))),
        'clergy',greatest(0,least(100,coalesce((p_loyalty->>'clergy')::numeric,100))),
        'burghers',greatest(0,least(100,coalesce((p_loyalty->>'burghers')::numeric,100))),
        'peasants',greatest(0,least(100,coalesce((p_loyalty->>'peasants')::numeric,100))));
    insert into public.territory_loyalty(territory_type,territory_id,loyalty,updated_at)
    values(p_territory_type,p_territory_id,normalized,now())
    on conflict(territory_type,territory_id) do update set loyalty=excluded.loyalty,updated_at=now();
    return normalized;
end;
$function$;
revoke all on function public.save_territory_loyalty(text,bigint,jsonb) from public,anon;
grant execute on function public.save_territory_loyalty(text,bigint,jsonb) to authenticated;

create or replace function public.apply_economy_turn(p_payload jsonb)
returns jsonb language plpgsql security definer set search_path = ''
as $function$
declare
    caller_role text;
    cal public.game_calendar%rowtype;
    row_data jsonb;
    owner_name text;
    report_data jsonb;
    treasury_delta numeric;
    local_loyalty jsonb;
begin
    select p.role into caller_role from public.profiles p where p.id=(select auth.uid());
    if caller_role is distinct from 'admin' then raise exception 'Only an administrator can advance the game turn' using errcode='42501'; end if;
    select * into cal from public.game_calendar where singleton=true for update;
    if p_payload->'processed_calendar'->>'turn' is distinct from cal.turn::text
       or p_payload->'processed_calendar'->>'season' is distinct from cal.season
       or p_payload->'processed_calendar'->>'year' is distinct from cal.year::text then
        raise exception 'Calendar changed; reload and recalculate the turn' using errcode='40001';
    end if;
    if jsonb_typeof(p_payload->'inventoryUpdates')<>'array' or jsonb_typeof(p_payload->'provinceUpdates')<>'array'
       or jsonb_typeof(p_payload->'markerUpdates')<>'array' or jsonb_typeof(p_payload->'territoryLoyaltyUpdates')<>'array'
       or jsonb_typeof(p_payload->'ownerReports')<>'object' or jsonb_typeof(p_payload->'treasuryAdjustments')<>'object'
       or jsonb_array_length(p_payload->'inventoryUpdates')>20000 or jsonb_array_length(p_payload->'provinceUpdates')>1000
       or jsonb_array_length(p_payload->'markerUpdates')>1000 or jsonb_array_length(p_payload->'territoryLoyaltyUpdates')>2000 then raise exception 'Invalid economy payload'; end if;

    delete from public.marker_inventories;
    for row_data in select value from jsonb_array_elements(p_payload->'inventoryUpdates') loop
        if (row_data->>'quantity')::numeric<0 or row_data->>'item_type' not in ('resource','good') then raise exception 'Invalid inventory row'; end if;
        insert into public.marker_inventories(marker_id,item_type,item_name,quantity)
        values((row_data->>'marker_id')::bigint,row_data->>'item_type',row_data->>'item_name',(row_data->>'quantity')::numeric)
        on conflict(marker_id,item_type,item_name) do update set quantity=excluded.quantity;
    end loop;
    for row_data in select value from jsonb_array_elements(p_payload->'provinceUpdates') loop
        if coalesce((row_data->>'yards')::numeric,0)<0 or coalesce((row_data->>'stored_resource_qty')::numeric,0)<0 then raise exception 'Invalid province state'; end if;
        update public."Provinces" set yards=coalesce((row_data->>'yards')::bigint,yards),target_marker_id=nullif(row_data->>'target_marker_id','')::bigint,
            stored_resource_qty=(row_data->>'stored_resource_qty')::numeric where id=(row_data->>'id')::bigint;
    end loop;
    for row_data in select value from jsonb_array_elements(p_payload->'markerUpdates') loop
        if coalesce((row_data->>'yards')::numeric,0)<0 then raise exception 'Invalid settlement population'; end if;
        update public.markers set yards=coalesce((row_data->>'yards')::bigint,yards) where id=(row_data->>'id')::bigint;
    end loop;
    for row_data in select value from jsonb_array_elements(p_payload->'territoryLoyaltyUpdates') loop
        if row_data->>'territory_type' not in ('province','marker') then raise exception 'Invalid loyalty territory'; end if;
        local_loyalty=jsonb_build_object(
            'aristocracy',greatest(0,least(100,coalesce((row_data->'loyalty'->>'aristocracy')::numeric,100))),
            'clergy',greatest(0,least(100,coalesce((row_data->'loyalty'->>'clergy')::numeric,100))),
            'burghers',greatest(0,least(100,coalesce((row_data->'loyalty'->>'burghers')::numeric,100))),
            'peasants',greatest(0,least(100,coalesce((row_data->'loyalty'->>'peasants')::numeric,100))));
        insert into public.territory_loyalty(territory_type,territory_id,loyalty,updated_at)
        values(row_data->>'territory_type',(row_data->>'territory_id')::bigint,local_loyalty,now())
        on conflict(territory_type,territory_id) do update set loyalty=excluded.loyalty,updated_at=now();
    end loop;
    for owner_name,report_data in select key,value from jsonb_each(p_payload->'ownerReports') loop
        insert into public.turn_economy_reports(owner,turn,season,year,report) values(owner_name,cal.turn,cal.season,cal.year,report_data)
        on conflict(owner,turn,season,year) do update set report=excluded.report,created_at=now();
    end loop;
    for owner_name,report_data in select key,value from jsonb_each(p_payload->'treasuryAdjustments') loop
        treasury_delta=report_data::text::numeric;
        update public.state_mechanics sm set settings=sm.settings||jsonb_build_object('economy',coalesce(sm.settings->'economy','{}'::jsonb)||jsonb_build_object('treasury',greatest(0,coalesce((sm.settings#>>'{economy,treasury}')::numeric,0)+treasury_delta))),updated_at=now()
        where sm.owner=owner_name and treasury_delta<>0;
    end loop;
    update public.game_calendar set turn=cal.turn+1,year=cal.year+case when cal.season='Осень' then 1 else 0 end,
        season=case cal.season when 'Осень' then 'Зима' when 'Зима' then 'Весна' when 'Весна' then 'Лето' else 'Осень' end,
        updated_at=now() where singleton=true returning * into cal;
    if cal.year>(p_payload->'processed_calendar'->>'year')::integer then
        update public.state_mechanics sm set settings=jsonb_set(sm.settings,'{ruler,age}',to_jsonb(least(150,coalesce((sm.settings#>>'{ruler,age}')::integer,0)+1)),true),updated_at=now()
        where sm.settings?'ruler' and sm.settings#>'{ruler}' is not null;
    end if;
    return jsonb_build_object('turn',cal.turn,'season',cal.season,'year',cal.year);
end;
$function$;
revoke all on function public.apply_economy_turn(jsonb) from public,anon;
grant execute on function public.apply_economy_turn(jsonb) to authenticated;
