create table if not exists public.state_trade_contracts (
    id bigint generated by default as identity primary key,
    seller_owner text not null references public.state_mechanics(owner) on update cascade on delete cascade,
    buyer_owner text not null references public.state_mechanics(owner) on update cascade on delete cascade,
    source_marker_id bigint not null references public.markers(id) on delete cascade,
    destination_marker_id bigint not null references public.markers(id) on delete cascade,
    item_type text not null check (item_type in ('resource','good')),
    item_name text not null,
    quantity_per_turn numeric not null check (quantity_per_turn > 0 and quantity_per_turn <= 10000),
    unit_price numeric not null check (unit_price >= 0 and unit_price <= 1000000),
    status text not null default 'pending' check (status in ('pending','active','rejected','cancelled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint state_trade_contract_parties_differ check (seller_owner <> buyer_owner),
    constraint state_trade_contract_item_name check (item_name in (
        'Зерно','Древесина','Железная руда','Скот','Камень','Соль','Пушнина','Бивни','Ворвань','Самоцветы','Мёд и Воск','Лён','Морепродукты',
        'Топливо','Сукно и Одежда','Инструменты','Оружие и Доспехи','Обработанный камень','Оловина','Бумага'
    ))
);

alter table public.state_trade_contracts enable row level security;
grant select on public.state_trade_contracts to anon, authenticated;
drop policy if exists state_trade_contracts_read_participants on public.state_trade_contracts;
create policy state_trade_contracts_read_participants on public.state_trade_contracts for select to authenticated
using (
    exists (select 1 from public.profiles p where p.id=(select auth.uid()) and (p.role='admin' or p.owner in (seller_owner,buyer_owner)))
);

create or replace function public.save_state_trade_contract(
    p_action text,
    p_contract_id bigint default null,
    p_source_marker_id bigint default null,
    p_destination_marker_id bigint default null,
    p_item_type text default null,
    p_item_name text default null,
    p_quantity_per_turn numeric default null,
    p_unit_price numeric default null
) returns jsonb
language plpgsql security definer set search_path = ''
as $function$
declare
    caller_owner text;
    caller_role text;
    source_row public.markers%rowtype;
    destination_row public.markers%rowtype;
    contract_row public.state_trade_contracts%rowtype;
begin
    select p.owner,p.role into caller_owner,caller_role from public.profiles p where p.id=(select auth.uid());
    if caller_role is null then raise exception 'Authentication required' using errcode='42501'; end if;
    if p_action='offer' then
        select * into source_row from public.markers where id=p_source_marker_id;
        select * into destination_row from public.markers where id=p_destination_marker_id;
        if source_row.id is null or destination_row.id is null or source_row.type='ruins' or destination_row.type='ruins'
           or source_row.owner is null or destination_row.owner is null or source_row.owner=destination_row.owner then
            raise exception 'Choose valid settlements belonging to different states';
        end if;
        if caller_role<>'admin' and source_row.owner is distinct from caller_owner then raise exception 'Only the seller state can offer this contract' using errcode='42501'; end if;
        if p_item_type not in ('resource','good') or p_item_name not in (
            'Зерно','Древесина','Железная руда','Скот','Камень','Соль','Пушнина','Бивни','Ворвань','Самоцветы','Мёд и Воск','Лён','Морепродукты',
            'Топливо','Сукно и Одежда','Инструменты','Оружие и Доспехи','Обработанный камень','Оловина','Бумага'
        ) then raise exception 'Invalid trade cargo'; end if;
        if (p_item_type='resource' and p_item_name not in ('Зерно','Древесина','Железная руда','Скот','Камень','Соль','Пушнина','Бивни','Ворвань','Самоцветы','Мёд и Воск','Лён','Морепродукты'))
           or (p_item_type='good' and p_item_name not in ('Топливо','Сукно и Одежда','Инструменты','Оружие и Доспехи','Обработанный камень','Оловина','Бумага')) then raise exception 'Cargo does not match cargo type'; end if;
        if coalesce(p_quantity_per_turn,0)<=0 or p_quantity_per_turn>10000 or coalesce(p_unit_price,-1)<0 or p_unit_price>1000000 then raise exception 'Invalid trade terms'; end if;
        insert into public.state_trade_contracts(seller_owner,buyer_owner,source_marker_id,destination_marker_id,item_type,item_name,quantity_per_turn,unit_price)
        values(source_row.owner,destination_row.owner,source_row.id,destination_row.id,p_item_type,p_item_name,p_quantity_per_turn,p_unit_price) returning * into contract_row;
        return to_jsonb(contract_row);
    elsif p_action in ('accept','reject','cancel') then
        select * into contract_row from public.state_trade_contracts where id=p_contract_id for update;
        if contract_row.id is null then raise exception 'Trade offer not found'; end if;
        if contract_row.status not in ('pending','active') then raise exception 'Trade offer is already closed'; end if;
        if p_action in ('accept','reject') then
            if caller_role<>'admin' and caller_owner is distinct from contract_row.buyer_owner then raise exception 'Only the buyer state can respond' using errcode='42501'; end if;
            if contract_row.status<>'pending' then raise exception 'Only pending offers can be accepted or rejected'; end if;
            update public.state_trade_contracts set status=case when p_action='accept' then 'active' else 'rejected' end,updated_at=now() where id=p_contract_id returning * into contract_row;
        else
            if caller_role<>'admin' and caller_owner is distinct from contract_row.seller_owner then raise exception 'Only the seller state can cancel' using errcode='42501'; end if;
            update public.state_trade_contracts set status='cancelled',updated_at=now() where id=p_contract_id returning * into contract_row;
        end if;
        return to_jsonb(contract_row);
    end if;
    raise exception 'Unknown trade contract action';
end;
$function$;
revoke all on function public.save_state_trade_contract(text,bigint,bigint,bigint,text,text,numeric,numeric) from public,anon;
grant execute on function public.save_state_trade_contract(text,bigint,bigint,bigint,text,text,numeric,numeric) to authenticated;
